### ISSUE TITLE
doesn't run with lua 5.4.4

### ISSUE THREAD

**Issue by scrumit** [uleelx/ledis#1]
I am working on a Macbook with M1 processor (ARM). 

Mac Brew has installed lua 5.4.4 and I can edit some of the requires to make them find source code but I think this is assuming only luajit. Require'core'

And Luajit doesn't currently build on ARM. Well, not via homebrew.

**Comment by mystery-z** [comment]
@scrumit You need to install luajit from source on M1 / ARM, you can just get it from their website. 

@uleelx is there any reason ledis doesn't support 5.4.x? I'm working on a project right now and I think this maybe what I'm looking for, but can't use it because of version issues...

**Comment by uleelx** [comment]
> @scrumit You need to install luajit from source on M1 / ARM, you can just get it from their website.
> 
> @uleelx is there any reason ledis doesn't support 5.4.x? I'm working on a project right now and I think this maybe what I'm looking for, but can't use it because of version issues...

Use LuaSocket 3.0.0 for Lua 5.4.3+ @scrumit @mystery-z 
See latest commit.
